export const API_BASE = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4100';

// Phase 4 §1 — Privy access-token injector.
// Set from the Privy provider boundary (usePrivy().getAccessToken).
// When set, request() auto-attaches `Authorization: Bearer <token>`.
let _getAuthToken: (() => Promise<string | null>) | null = null;

export function setAuthTokenGetter(fn: (() => Promise<string | null>) | null): void {
  _getAuthToken = fn;
}

// E2E dev bypass (see lib/auth.ts) — attaches the dev identity header
// the API honors only with its own DEV_AUTH_BYPASS=1 and never in prod.
const DEV_BYPASS_HEADER: Record<string, string> =
  process.env.NEXT_PUBLIC_DEV_AUTH_BYPASS === '1'
    ? { 'x-dev-user-email': 'e2e@41r.local' }
    : {};

async function request<T>(path: string, options?: RequestInit): Promise<T> {
  // Spread options *first* so explicit headers merge on top — otherwise
  // `...options` at the end wipes the Content-Type we just set and the
  // server's json parser skips the body.
  const token = _getAuthToken ? await _getAuthToken().catch(() => null) : null;
  const res = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: {
      'Content-Type': 'application/json',
      'ngrok-skip-browser-warning': '1',
      ...DEV_BYPASS_HEADER,
      ...(token ? { Authorization: `Bearer ${token}` } : {}),
      ...options?.headers,
    },
  });
  if (!res.ok) {
    const error = await res.json().catch(() => ({ error: res.statusText }));
    throw new Error(error.error || `Request failed: ${res.status}`);
  }
  return res.json();
}

// ─── Scan API (Audience-Fit Validator) ─────────────────────────
// POST /api/scan creates a pending scan and returns scanId.
// GET  /api/scan/:id/report returns shape used by /validator/report/[id].
// `result` is null while the scan is still running; the report page
// renders an "in progress" state in that case.
export type ScanPersonaCard = {
  id: string;
  name: string;
  age: number;
  role: string;
  score: number | null;
  quote: string;
  tags: string[];
  is_synthetic: boolean;
};

export type ScanRecentResponse = {
  persona_id: string;
  cohort_id: string;
  cohort_label: string;
  age_group: string;
  voice: string;
  sentiment: 'positive' | 'mixed' | 'friction';
  created_at: string;
};

export type ScanCohortProgress = {
  cohort_id: string;
  cohort_label: string;
  n_completed: number;
  n_target: number;
};

export type ScanFriction = {
  rank: number;
  title: string;
  detail: string;
  n: number;
  where: string;
  impact: string;
  quote: string;
};

/** Phase 5 — Site-specific human-survey question generated by Haiku
 *  at scan time. The survey page renders these alongside the fixed
 *  §11.1 question set; respondents' answers land in
 *  survey_responses.custom_answers keyed by `id`. */
export type CustomQuestion = {
  id: string;
  type: 'likert' | 'text';
  question: string;
  dimension_hint?:
    | 'engagement'
    | 'task_success'
    | 'happiness'
    | 'adoption'
    | 'retention';
};

export type ScanReport = {
  scan: {
    id: string;
    target_url: string;
    category: string | null;
    category_confidence: number | null;
    one_line_pitch: string | null;
    mode: 'A' | 'B';
    status:
      | 'pending'
      | 'capturing'
      | 'sampling'
      | 'responding'
      | 'aggregating'
      | 'completed'
      | 'failed';
    personas_attempted: number;
    personas_completed: number;
    personas_flagged: number;
    weights_version: string | null;
    target_audience_text: string | null;
    mode_b_verdict: 'pass' | 'conditional' | 'fail' | null;
    mode_b_parsed_selector: unknown;
    /** Phase 5 — Site-specific human-survey questions generated by
     *  Haiku at scan time. Null when generation failed or hasn't run. */
    custom_questions: CustomQuestion[] | null;
    /** Ch1 objective page facts measured at capture (no LLM, 2026-06-10
     *  behavior-sim spike transfer). Null on legacy scans → strip hides. */
    capture_signals: {
      visible_word_count: number;
      link_count: number;
      cta_count: number;
      nav_menu_labels: string[];
      popup_detected: boolean;
      login_wall: boolean;
    } | null;
    created_at: string;
    completed_at: string | null;
  };
  result: {
    audience_fit_score: number;
    best: { cohort_id: string; cohort_label: string; cohort_fit_score: number };
    worst: { cohort_id: string; cohort_label: string; cohort_fit_score: number };
    median_score: number;
    global_task_success_avg: number;
    global_sentiment_avg: number;
    /** Acquisition Layer v1.1 — visitor-weighted parallel view.
     *  Mode A only; null when no cohort data or Mode B. */
    weighted?: {
      audience_fit_score: number;
      best: {
        cohort_id: string;
        cohort_label: string;
        cohort_fit_score: number;
        arrival_share: number;
        abandon_rate: number;
      };
      worst: {
        cohort_id: string;
        cohort_label: string;
        cohort_fit_score: number;
        arrival_share: number;
        abandon_rate: number;
      };
      median_score: number;
      global_task_success_avg: number;
      global_sentiment_avg: number;
      priors_source: string;
      priors_confidence: number;
    } | null;
  } | null;
  cohorts: unknown[] | null;
  fit_personas: ScanPersonaCard[] | null;
  non_fit_personas: ScanPersonaCard[] | null;
  frictions: ScanFriction[] | null;
  retention_curve: { d: string; v: number }[] | null;
  dimension_breakdown:
    | { l: string; v: number; sub: string; tone: string; suffix?: string; invert?: boolean }[]
    | null;
  formula_rows: { d: string; s: number; w: number; c: number }[] | null;
  kpis: { l: string; v: string; sub: string; tone: string }[] | null;
  aarrr: {
    total_personas: number;
    stages: {
      key: 'acquisition' | 'activation' | 'retention' | 'referral' | 'revenue';
      label: string;
      score: number;
      n_passing: number;
      total: number;
      threshold: string;
    }[];
  } | null;
  /** Acquisition Layer v1.1 — visitor-weighted AARRR. Mode A only. */
  aarrr_weighted?: {
    total_personas: number;
    stages: {
      key: 'acquisition' | 'activation' | 'retention' | 'referral' | 'revenue';
      label: string;
      score: number;
      n_passing: number;
      total: number;
      threshold: string;
    }[];
  } | null;
  recent_responses: ScanRecentResponse[];
  cohort_progress: ScanCohortProgress[];
  /** Phase 5 — live count of human survey responses. Drives the
   *  "Compare with humans (n=X)" footer button on the report page. */
  survey_response_count: number;
  /** Console S2 — false once the per-scan reward cap (30) is reached.
   *  The survey page MUST disclose this before the respondent answers
   *  (§12 decision 7 — trust over response rate). */
  survey_reward_available: boolean;
  /** Phase 5 — whether human_aggregate has been computed at least
   *  once. Lets the Compare button decide whether to land directly
   *  on the comparison page or trigger a recompute first. */
  human_aggregate_computed: boolean;
  /** Chain wiring Phase 2 — Seal-encrypted report blob on Walrus.
   *  Null until anchored at scan completion. */
  report_anchor?: {
    walrus_blob_id: string;
    walrus_url: string;
    anchored_at: string | null;
  } | null;
};

export type ScanPersonaDetail = {
  scan: {
    id: string;
    target_url: string;
    mode: 'A' | 'B';
    status: string;
  };
  persona: {
    id: string;
    display_name: string;
    tester_addr: string;
    age: number;
    age_group: string;
    cohort_id: string;
    cohort_label: string;
    voice_sample: string | null;
    vector_axes: { k: string; v: number }[];
    /** On-chain anchor (chain wiring). Null until anchored on Sui testnet. */
    chain: {
      sui_object_id: string;
      walrus_blob_id: string | null;
      seal_id: string | null;
      anchored_at: string | null;
      object_url: string;
      walrus_url: string | null;
    } | null;
  };
  response: {
    happiness: number | null;
    engagement: number | null;
    task_success: number | null;
    retention_d7: number | null;
    adoption: number | null;
    retention_d_curve: { d1: number; d3: number; d7: number; d30: number } | null;
    sus_responses: number[] | null;
    sus_raw_score: number | null;
    signup_likelihood: number | null;
    completion_likelihood: number | null;
    voice_first_impression: string | null;
    voice_friction: string | null;
    voice_biggest_friction: string | null;
    voice_would_return_because: string | null;
    is_flagged: boolean;
    flag_reason: string | null;
  };
};

/** Lightweight scan summary used by the public homepage feeds
 *  (Recent / Top / Live). Per Phase 2 §8.1 / P2-4. */
export type ScanSummary = {
  id: string;
  target_url: string;
  category: string | null;
  one_line_pitch: string | null;
  audience_fit_score: number | null;
  best_cohort_id: string | null;
  best_cohort_label: string | null;
  best_cohort_score: number | null;
  mode: 'A' | 'B';
  status: string;
  personas_completed: number;
  created_at: string;
  completed_at: string | null;
};

// ─── Phase 5 — AI vs Human comparison report ───────────────────
export type HumanAggregate = {
  n_respondents: number;
  audience_fit_score: number;
  dimension_means: {
    happiness: number;
    task_success: number;
    adoption: number;
    retention_d7: number;
    engagement: number;
  };
  frictions: Array<{
    rank: number;
    title: string;
    summary: string;
    n: number;
    where: string;
    impact: string;
    quote: string;
    affected_cohorts: string[];
  }> | null;
  aarrr: {
    total_personas: number;
    stages: Array<{
      key: 'acquisition' | 'activation' | 'retention' | 'referral' | 'revenue';
      label: string;
      score: number;
      n_passing: number;
      total: number;
      threshold: string;
    }>;
  } | null;
  custom_question_rollup: Record<
    string,
    { likert?: { mean: number; n_answered: number }; quotes?: string[] }
  >;
  computed_at: string;
};

export type ScanCompareReport = {
  scan: {
    id: string;
    target_url: string;
    category: string | null;
    one_line_pitch: string | null;
    mode: 'A' | 'B';
    status: string;
    custom_questions: CustomQuestion[] | null;
  };
  ai: {
    audience_fit_score: number | null;
    dimension_means: HumanAggregate['dimension_means'];
    frictions: Array<{ rank: number; title: string; n: number }>;
    n_personas: number;
  };
  /** null until POST /:id/human-aggregate has been triggered. */
  human: HumanAggregate | null;
  /** null when human is null. */
  diff: {
    audience_fit_delta: number;
    dimension_deltas: HumanAggregate['dimension_means'];
    /** 0..1 — fraction of AI clusters with at least one matching token in the human cluster titles. */
    friction_overlap: number;
    ai_only_frictions: Array<{ rank: number; title: string; n: number }>;
    human_only_frictions: Array<{ rank: number; title: string; n: number }>;
  } | null;
  /** Live count of survey_responses rows for this scan — independent
   *  of human.n_respondents (which is frozen at last compute). */
  survey_response_count: number;
  /** Per-cohort AI↔human fidelity (Stage 1/T0 PoC). By-cohort |Δ|, never
   *  a single mixed-cohort number. cohort.delta/absDeltaMean are null
   *  until that cohort has BOTH AI personas and matched humans. */
  fidelity: {
    nAiPersonas: number;
    nHumans: number;
    nHumansMatched: number;
    nHumansUnmatched: number;
    overallAbsDeltaMean: number | null;
    nCohortsCompared: number;
    cohorts: Array<{
      cohortId: string;
      cohortLabel: string;
      nAi: number;
      nHuman: number;
      delta: {
        happiness: number;
        engagement: number;
        adoption: number;
        retentionD7: number;
        taskSuccess: number;
      } | null;
      absDeltaMean: number | null;
      matchConfidenceMean: number | null;
    }>;
  } | null;
};

export const scanApi = {
  createScan: (body: {
    target_url: string;
    mode?: 'A' | 'B';
    target_audience_text?: string;
    hypothesis?: string;
    /** Mode A only — restrict the analysis to a subset of the 8
     *  STANDARD_COHORTS by id. Omit / empty to run all 8. */
    target_cohorts?: string[];
    /** Payment rail. Default 'credits' (off-chain). 'usdc' → the response
     *  carries an `escrow` envelope; pay it via payScan. */
    payment_method?: 'credits' | 'usdc';
  }) =>
    request<{
      scanId: string;
      status: string;
      escrow?: {
        usdc_amount: string;
        coin_type: string;
        cap_recipient: string;
        package_id: string;
        target: string;
        criteria: string;
      };
    }>('/api/scan', {
      method: 'POST',
      body: JSON.stringify(body),
    }),

  /** Step 2 of the USDC escrow flow: submit the on-chain create-tx digest +
   *  campaign/cap object ids; the server verifies + starts the scan. */
  payScan: (
    scanId: string,
    body: { sui_digest: string; campaign_object_id: string; cap_id: string },
  ) =>
    request<{ scanId: string; status: string; escrow_status: string }>(
      `/api/scan/${scanId}/pay`,
      { method: 'POST', body: JSON.stringify(body) },
    ),

  getReport: (id: string) => request<ScanReport>(`/api/scan/${id}/report`),

  getPersona: (scanId: string, personaId: string) =>
    request<ScanPersonaDetail>(`/api/scan/${scanId}/persona/${personaId}`),

  /** Recent 20 completed scans (newest first). */
  getRecent: () => request<{ scans: ScanSummary[] }>('/api/scan/recent'),

  /** Top 10 scans by audience_fit_score (descending). */
  getTop: () => request<{ scans: ScanSummary[] }>('/api/scan/top'),

  /** Currently in-flight scans (capturing/sampling/responding/aggregating). */
  getLive: () => request<{ scans: ScanSummary[] }>('/api/scan/live'),

  /** Auth-gated list of scans owned by the current user.
   *  Console S2 adds workspace_id (null = the console's Unassigned bucket).
   *  (Solana payment receipt fields removed in the Sui migration.) */
  getMyScans: () =>
    request<{
      scans: Array<ScanSummary & {
        workspace_id: string | null;
      }>;
    }>('/api/scan/me'),

  /** Submit a human survey for an already-completed scan.
   *  Phase 5.1 — requires Privy auth (the AuthBridge attaches the
   *  bearer token via request()). Identity is taken from the token,
   *  not the body. Re-submissions upsert (one row per scan, user) so
   *  the user can edit their answer later. */
  submitSurvey: (
    scanId: string,
    body: {
      sus_responses: number[]; // length 10, each 1-5
      engagement_category: 'abandon' | 'skim' | 'browse' | 'engage' | 'extended';
      signup_likelihood: number; // 0-1
      retention_category: 'no_return' | 'weak' | 'moderate' | 'strong';
      completion_likelihood: number; // 0-1
      voice: {
        first_impression?: string;
        biggest_friction?: string;
        would_return_because?: string;
        if_could_change_one_thing?: string;
      };
      demographics: {
        age_group: 'teen' | 'young_adult' | 'adult' | 'senior';
        tech_literacy: number; // 0-1
        crypto_experience: number; // 0-1
        mobile_first: boolean;
      };
      /** Phase 5 — Per-scan custom-question answers, keyed by question
       *  id (e.g. "cq1"). Likert answers are ints 1-5; text answers
       *  are strings. Optional/empty when the scan has no custom
       *  questions or the respondent skipped the section. */
      custom_answers?: Record<string, number | string>;
    },
  ) =>
    request<{
      ok: boolean;
      scanId: string;
      rows_created: number;
      summary: {
        llm: Record<string, number>;
        human: Record<string, number>;
        delta: Record<string, number>;
      };
    }>(`/api/scan/${scanId}/survey`, {
      method: 'POST',
      body: JSON.stringify(body),
    }),

  /** Phase 5 — Manually trigger human-aggregate recompute. Idempotent
   *  on the server; safe to call multiple times. Returns 409
   *  no_responses when survey_responses is empty for the scan. */
  recomputeHumanAggregate: (scanId: string) =>
    request<{ ok: boolean; aggregate: HumanAggregate }>(
      `/api/scan/${scanId}/human-aggregate`,
      { method: 'POST', body: '{}' },
    ),

  /** Phase 5 — Read combined AI + human + diff report. `human` and
   *  `diff` are null until recomputeHumanAggregate has been called. */
  getCompareReport: (scanId: string) =>
    request<ScanCompareReport>(`/api/scan/${scanId}/compare`),
};

// ─── Phase 5.1 — My survey responses ────────────────────────────
export type MySurveyResponseSummary = {
  scan_id: string;
  submitted_at: string;
  target_url: string;
  category: string | null;
  one_line_pitch: string | null;
  scan_status: string;
  ai_audience_fit_score: number | null;
};

export type MySurveyResponseDetail = {
  scan: {
    id: string;
    target_url: string;
    category: string | null;
    one_line_pitch: string | null;
    mode: 'A' | 'B';
    status: string;
    ai_audience_fit_score: number | null;
    custom_questions: CustomQuestion[] | null;
  };
  response: {
    submitted_at: string;
    sus_responses: number[];
    dimension_inputs: {
      engagement_category: 'abandon' | 'skim' | 'browse' | 'engage' | 'extended';
      signup_likelihood: number;
      retention_category: 'no_return' | 'weak' | 'moderate' | 'strong';
      completion_likelihood: number;
    };
    voice: {
      first_impression?: string;
      biggest_friction?: string;
      would_return_because?: string;
      if_could_change_one_thing?: string;
    };
    custom_answers: Record<string, number | string>;
    demographics: {
      age_group: 'teen' | 'young_adult' | 'adult' | 'senior';
      tech_literacy: number;
      crypto_experience: number;
      mobile_first: boolean;
    };
  };
  me_scores: {
    happiness: number;
    task_success: number;
    adoption: number;
    retention_d7: number;
    engagement: number;
  };
  ai_scores: {
    happiness: number;
    task_success: number;
    adoption: number;
    retention_d7: number;
    engagement: number;
  };
  /** Per-dimension delta = me_scores - ai_scores. Positive values mean
   *  the human rated this dimension higher than the AI consensus did. */
  dimension_deltas: {
    happiness: number;
    task_success: number;
    adoption: number;
    retention_d7: number;
    engagement: number;
  };
};

// ─── Founder Console workspaces (Console Sprint 2) ──────────────
export type ConsoleSite = {
  id: string;
  url_host: string;
  name: string | null;
  /** Public tracking key — GA measurement-id semantics, safe in markup. */
  site_key: string;
  secret_last4: string;
  /** Anchor scan — the analysis partner surveys auto-attach to. null
   *  until this site's first scan completes. */
  anchor_scan_id: string | null;
  /** Authenticated capture (Phase 1): whether an encrypted session is
   *  stored (never the session itself) + the key screens to capture. */
  has_auth_session: boolean;
  auth_session_updated_at: string | null;
  capture_paths: string[] | null;
  capture_mobile: boolean;
  intended_stage: "onboarding" | "main_app" | "any";
  /** Emergent tier: a beacon has arrived through this site_key. */
  tracked: boolean;
  last_event_at: string | null;
  created_at: string;
};

export type ConsoleSiteListItem = ConsoleSite & {
  scan_count: number;
  latest_score: number | null;
  prev_score: number | null;
  latest_category: string | null;
  best_cohort_id: string | null;
  last_scan_at: string | null;
};

export const consoleApi = {
  listSites: () =>
    request<{ sites: ConsoleSiteListItem[] }>(`/api/console/sites`),

  /** 1-step registration. `secret` is plaintext EXACTLY ONCE — the
   *  server only keeps the hash. */
  createSite: (body: { url: string; name?: string }) =>
    request<{ workspace: ConsoleSite; secret: string }>(`/api/console/sites`, {
      method: 'POST',
      body: JSON.stringify(body),
    }),

  getSite: (id: string) =>
    request<{ workspace: ConsoleSite; scans: ScanSummary[] }>(
      `/api/console/sites/${id}`,
    ),

  updateSite: (id: string, body: { url?: string; name?: string | null }) =>
    request<{ workspace: ConsoleSite }>(`/api/console/sites/${id}`, {
      method: 'PATCH',
      body: JSON.stringify(body),
    }),

  deleteSite: (id: string) =>
    request<{ ok: boolean }>(`/api/console/sites/${id}`, { method: 'DELETE' }),

  /** Invalidates the old secret immediately; new plaintext once. */
  rotateKey: (id: string) =>
    request<{ ok: boolean; secret: string; secret_last4: string }>(
      `/api/console/sites/${id}/rotate-key`,
      { method: 'POST', body: '{}' },
    ),

  linkScan: (id: string, scanId: string) =>
    request<{ ok: boolean }>(`/api/console/sites/${id}/link-scan`, {
      method: 'POST',
      body: JSON.stringify({ scan_id: scanId }),
    }),

  /** Console S3 — measured tracking aggregates for the analytics tab. */
  getAnalytics: (id: string, days: 7 | 30 = 7) =>
    request<SiteAnalytics>(`/api/console/sites/${id}/analytics?days=${days}`),

  /** Authenticated capture (Phase 1) — store the encrypted session +
   *  key screens so scans of this gated site reach the real product. */
  setAuthSession: (
    id: string,
    body: {
      storage_state: string;
      capture_paths?: string[];
      capture_mobile?: boolean;
      intended_stage?: "onboarding" | "main_app" | "any";
    },
  ) =>
    request<{ ok: boolean }>(`/api/console/sites/${id}/auth-session`, {
      method: 'PUT',
      body: JSON.stringify(body),
    }),

  clearAuthSession: (id: string) =>
    request<{ ok: boolean }>(`/api/console/sites/${id}/auth-session`, {
      method: 'DELETE',
    }),
};

export type SiteAnalytics = {
  days: number;
  kpis: {
    visitors: number;
    sessions: number;
    pageviews: number;
    avg_dwell_ms: number;
  };
  daily: Array<{ day: string; visitors: number; pageviews: number }>;
  paths: Array<{
    path: string;
    views: number;
    avg_dwell_ms: number;
    avg_scroll_pct: number;
  }>;
  events_this_month: number;
  monthly_soft_cap: number;
};

// ─── Tester points + founder credits (Console Sprint 1) ─────────
export type MyPoints = {
  balance: number;
  transactions: Array<{
    amount: number;
    reason: string;
    source: string;
    created_at: string;
  }>;
};

export type MyCredits = {
  balance_cents: number;
  transactions: Array<{
    amount_cents: number;
    reason: string;
    ref_id: string | null;
    expires_at: string | null;
    created_at: string;
  }>;
};

export const meApi = {
  /** Phase 5.1 — list of survey responses the current Privy user has
   *  submitted. Filtered server-side by user_id. */
  listMySurveyResponses: () =>
    request<{ responses: MySurveyResponseSummary[] }>(
      `/api/me/survey-responses`,
    ),

  /** Phase 5.1 — detailed view of one of the user's submissions, with
   *  AI-vs-Me dimension deltas pre-computed. 404 when the user hasn't
   *  submitted to that scan. */
  getMySurveyResponse: (scanId: string) =>
    request<MySurveyResponseDetail>(`/api/me/survey-responses/${scanId}`),

  /** Tester point ledger (partner pilot — earn side). */
  getPoints: () => request<MyPoints>(`/api/me/points`),

  /** Founder credit ledger (Console Sprint 1 — spend side). */
  getCredits: () => request<MyCredits>(`/api/me/credits`),
};

// ─── Calibration API (Phase 2-C-1) ─────────────────────────────
export type CalibrationReport = {
  period_start: string;
  period_end: string;
  totalRecords: number;
  correlations: {
    dimension: string;
    correlation: number | null;
    n: number;
    confidence: 'High' | 'Medium-High' | 'Medium' | 'Low-Medium' | 'Low' | 'n/a';
    change: string;
  }[];
  tracks: { key: string; source: string; n: number }[];
  versions: {
    v: string;
    d: string;
    hap: number;
    eng: number;
    tsk: number;
    ado: number;
    ret: number;
    current?: boolean;
  }[];
};

export const calibrationApi = {
  getCurrent: () => request<CalibrationReport>('/api/calibration/current'),
};

/** Partner hosted-survey submit. The signed `pt` handoff token
 *  replaces Privy auth — identity (email + scan id + workspace) lives
 *  inside the token, so no bearer header is needed. Generic since
 *  2026-06-12 (workspace-keyed; the geulbat-specific path is gone). */
export function submitSurveyByToken(
  token: string,
  body: Parameters<typeof scanApi.submitSurvey>[1],
) {
  return request<{ ok: boolean; first_submission: boolean; points_awarded: number }>(
    '/api/partner/survey-by-token',
    { method: 'POST', body: JSON.stringify({ ...body, token }) },
  );
}
